const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Relax in this charming beachfront cottage with ocean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80", // trending (Bali Jungle)
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: ["trending"],
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stylish loft apartment in the heart of the city.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80", // iconic (NYC)
    },
    price: 1200,
    location: "New York",
    country: "United States",
    category: ["iconic"],
    geometry: { type: "Point", coordinates: [-74.0060, 40.7128] },
  },
  {
    title: "Mountain Retreat Cabin",
    description: "Peaceful wooden cabin surrounded by mountains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80", // mountains (Aspen)
    },
    price: 900,
    location: "Aspen",
    country: "United States",
    category: ["mountains"],
    geometry: { type: "Point", coordinates: [-106.8370, 39.1911] },
  },
  {
    title: "Luxury Villa with Pool",
    description: "Private villa with infinity pool and sea view.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=80", // pools (Santorini)
    },
    price: 3000,
    location: "Santorini",
    country: "Greece",
    category: ["pools"],
    geometry: { type: "Point", coordinates: [25.4600, 36.3932] },
  },
  {
    title: "Desert Glamping Tent",
    description: "Experience luxury camping under the stars.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80", // camping (Jaisalmer)
    },
    price: 600,
    location: "Jaisalmer",
    country: "India",
    category: ["camping"],
    geometry: { type: "Point", coordinates: [69.3187, 26.9157] },
  },
  {
    title: "Lakefront Wooden House",
    description: "Beautiful house right next to a serene lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b41?auto=format&fit=crop&w=800&q=80", // pools (Zurich)
    },
    price: 1400,
    location: "Zurich",
    country: "Switzerland",
    category: ["pools"],
    geometry: { type: "Point", coordinates: [8.5417, 47.3769] },
  },
  {
    title: "Tokyo Studio Apartment",
    description: "Compact and modern studio in central Tokyo.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80", // iconic (Tokyo)
    },
    price: 1100,
    location: "Tokyo",
    country: "Japan",
    category: ["iconic"],
    geometry: { type: "Point", coordinates: [139.6917, 35.6895] },
  },
  {
    title: "Parisian Romantic Flat",
    description: "Cozy flat with Eiffel Tower views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80", // iconic (Paris)
    },
    price: 1800,
    location: "Paris",
    country: "France",
    category: ["iconic"],
    geometry: { type: "Point", coordinates: [2.3522, 48.8566] },
  },
  {
    title: "Countryside Farmhouse",
    description: "Traditional farmhouse surrounded by greenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80", // farms (Tuscany)
    },
    price: 800,
    location: "Tuscany",
    country: "Italy",
    category: ["farms"],
    geometry: { type: "Point", coordinates: [11.2558, 43.7696] },
  },
  {
    title: "Beach Shack in Goa",
    description: "Simple beachside shack perfect for sunsets.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80", // trending (Goa)
    },
    price: 500,
    location: "Goa",
    country: "India",
    category: ["trending"],
    geometry: { type: "Point", coordinates: [73.7636, 15.2993] },
  },
  {
    title: "Dubai Skyline Apartment",
    description: "Luxury apartment with Burj Khalifa view.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1492724441997-5dc865305da7",
    },
    price: 2500,
    location: "Dubai",
    country: "UAE",
    category: ["iconic", "rooms", "trending"],
    geometry: { type: "Point", coordinates: [55.2962, 25.276987] },
  },
  {
    title: "Bali Jungle Villa",
    description: "Private villa surrounded by tropical jungle.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    },
    price: 1700,
    location: "Bali",
    country: "Indonesia",
    category: ["pools", "trending", "rooms"],
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
  },
  {
    title: "London City Apartment",
    description: "Modern apartment in central London.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    },
    price: 2000,
    location: "London",
    country: "UK",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [-0.1276, 51.5074] },
  },
  {
    title: "Sydney Beach House",
    description: "Bright house near Bondi Beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    },
    price: 2100,
    location: "Sydney",
    country: "Australia",
    category: ["pools", "iconic"],
    geometry: { type: "Point", coordinates: [151.2093, -33.8688] },
  },
  {
    title: "Swiss Alps Chalet",
    description: "Snowy chalet with breathtaking mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1455587734955-081b22074882",
    },
    price: 1900,
    location: "Interlaken",
    country: "Switzerland",
    category: ["mountains", "arctic"],
    geometry: { type: "Point", coordinates: [7.8627, 46.6863] },
  },
  {
    title: "New Delhi Penthouse",
    description: "Luxury penthouse with city skyline view.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 1300,
    location: "New Delhi",
    country: "India",
    category: ["rooms", "trending"],
    geometry: { type: "Point", coordinates: [77.2090, 28.6139] },
  },
  {
    title: "Barcelona Seaside Flat",
    description: "Colorful flat near the Mediterranean coast.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505692794403-34d4982e5f16",
    },
    price: 1400,
    location: "Barcelona",
    country: "Spain",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [2.1734, 41.3851] },
  },
  {
    title: "Toronto Condo",
    description: "High-rise condo in downtown Toronto.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
    },
    price: 1250,
    location: "Toronto",
    country: "Canada",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [-79.3832, 43.6532] },
  },
  {
    title: "Cape Town Ocean Villa",
    description: "Stunning villa overlooking the Atlantic.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
    },
    price: 1600,
    location: "Cape Town",
    country: "South Africa",
    category: ["pools", "trending"],
    geometry: { type: "Point", coordinates: [18.4241, -33.9249] },
  },
  {
    title: "Iceland Glass Cabin",
    description: "Glass cabin perfect for northern lights.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c",
    },
    price: 1500,
    location: "Reykjavik",
    country: "Iceland",
    category: ["arctic", "mountains"],
    geometry: { type: "Point", coordinates: [-21.8174, 64.1265] },
  },

  {
    title: "Amsterdam Canal House",
    description: "Historic house along the canal.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1475856034135-6b0eacb5b4d8",
    },
    price: 1750,
    location: "Amsterdam",
    country: "Netherlands",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
  },
  {
    title: "Bangkok Highrise",
    description: "Modern apartment with city skyline view.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    },
    price: 900,
    location: "Bangkok",
    country: "Thailand",
    category: ["rooms", "trending"],
    geometry: { type: "Point", coordinates: [100.5018, 13.7563] },
  },
  {
    title: "Maldives Overwater Bungalow",
    description: "Stay above crystal clear waters.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 4000,
    location: "Maldives",
    country: "Maldives",
    category: ["pools", "trending"],
    geometry: { type: "Point", coordinates: [73.2207, -0.6815] },
  },
  {
    title: "San Francisco Townhouse",
    description: "Colorful townhouse near Golden Gate.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    },
    price: 2300,
    location: "San Francisco",
    country: "United States",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [-122.4194, 37.7749] },
  },
  {
    title: "Rio Beach Apartment",
    description: "Sunny apartment near Copacabana beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    },
    price: 1000,
    location: "Rio de Janeiro",
    country: "Brazil",
    category: ["pools", "trending"],
    geometry: { type: "Point", coordinates: [-43.1729, -22.9068] },
  },
  {
    title: "Himalayan Homestay",
    description: "Peaceful stay in the Himalayas.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000",
    },
    price: 700,
    location: "Manali",
    country: "India",
    category: ["mountains", "camping"],
    geometry: { type: "Point", coordinates: [77.1887, 32.2396] },
  },
  {
    title: "Seoul Smart Apartment",
    description: "Tech-enabled apartment in Gangnam.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    },
    price: 1200,
    location: "Seoul",
    country: "South Korea",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [127.0276, 37.4979] },
  },
  {
    title: "Lisbon Rooftop Flat",
    description: "Rooftop terrace with sunset view.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    },
    price: 1300,
    location: "Lisbon",
    country: "Portugal",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [-9.1427, 38.7369] },
  },
  {
    title: "Moscow Luxury Suite",
    description: "Elegant suite in central Moscow.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 1500,
    location: "Moscow",
    country: "Russia",
    category: ["iconic", "rooms"],
    geometry: { type: "Point", coordinates: [37.6173, 55.7558] },
  },
  {
    title: "Mexico City Loft",
    description: "Colorful loft in cultural district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
    },
    price: 850,
    location: "Mexico City",
    country: "Mexico",
    category: ["rooms", "trending"],
    geometry: { type: "Point", coordinates: [-99.1332, 19.4326] },
  },
];
module.exports = { data: sampleListings };